version: "3"
services: 
    elastalert:
        build: 
            context: .
        image: elastalert-local
        ports: 
        - 3030:3030
        volumes: 
        - ./config:/opt/config
        - ./rules:/opt/rules
        container_name: elastalert-local